export const products1 = [
  {
    id: 1,
    name: "iPhone",
    price: "$999",
    category: "electronics",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Samsung Galaxy",
    price: "$899",
    category: "electronics",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Macbook Pro",
    price: "$1,299",
    category: "electronics",
    availability: "Out of Stock",
  },
  {
    id: 4,
    name: "Lenovo ThinkPad",
    price: "$999",
    category: "electronics",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "T-Shirt",
    price: "$20",
    category: "clothing",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Jeans",
    price: "$50",
    category: "clothing",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Sweater",
    price: "$40",
    category: "clothing",
    availability: "Out of Stock",
  },
  {
    id: 8,
    name: "Hoodie",
    price: "$35",
    category: "clothing",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Pizza",
    price: "$12",
    category: "food",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Burger",
    price: "$8",
    category: "food",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Salad",
    price: "$6",
    category: "food",
    availability: "Out of Stock",
  },
  {
    id: 12,
    name: "Sushi",
    price: "$15",
    category: "food",
    availability: "In Stock",
  },
];
