export const events = [
  {
    id: 1,
    name: "Concert in the park",
    date: "2023-06-01",
    location: "Central Park",
    price: 25,
    type: "music",
  },
  {
    id: 2,
    name: "Basketball game",
    date: "2023-07-04",
    location: "Madison Square Garden",
    price: 50,
    type: "sports",
  },
  {
    id: 3,
    name: "Theater play",
    date: "2023-08-12",
    location: "Broadway Theater",
    price: 100,
    type: "theater",
  },
  {
    id: 4,
    name: "Rock concert",
    date: "2023-09-15",
    location: "Barclays Center",
    price: 75,
    type: "music",
  },
  {
    id: 5,
    name: "Soccer match",
    date: "2023-10-20",
    location: "Red Bull Arena",
    price: 40,
    type: "sports",
  },
  {
    id: 6,
    name: "Comedy show",
    date: "2023-11-25",
    location: "Comedy Cellar",
    price: 30,
    type: "theater",
  },
];
