export const moviesData = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    genre: "drama",
    releaseYear: 1994,
  },
  {
    id: 2,
    title: "The Godfather",
    director: "Francis Ford Coppola",
    genre: "drama",
    releaseYear: 1972,
  },
  {
    id: 3,
    title: "The Dark Knight",
    director: "Christopher Nolan",
    genre: "action",
    releaseYear: 2008,
  },
  {
    id: 4,
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    genre: "drama",
    releaseYear: 1994,
  },
  {
    id: 5,
    title: "The Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    genre: "action",
    releaseYear: 1999,
  },
  {
    id: 6,
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    genre: "thriller",
    releaseYear: 1991,
  },
  {
    id: 7,
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    genre: "fantasy",
    releaseYear: 2003,
  },
  {
    id: 8,
    title: "The Godfather: Part II",
    director: "Francis Ford Coppola",
    genre: "drama",
    releaseYear: 1974,
  },
  {
    id: 9,
    title: "The Lion King",
    director: "Roger Allers, Rob Minkoff",
    genre: "animation",
    releaseYear: 1994,
  },
  {
    id: 10,
    title: "The Terminator",
    director: "James Cameron",
    genre: "sci-fi",
    releaseYear: 1984,
  },
];
