export const books1 = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    publicationYear: "1960",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Fiction",
    publicationYear: "1949",
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Fiction",
    publicationYear: "1813",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    publicationYear: "1925",
  },
  {
    id: 5,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Fiction",
    publicationYear: "1951",
  },
  {
    id: 6,
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    genre: "Non-Fiction",
    publicationYear: "1947",
  },
  {
    id: 7,
    title: "Outliers: The Story of Success",
    author: "Malcolm Gladwell",
    genre: "Non-Fiction",
    publicationYear: "2008",
  },
  {
    id: 8,
    title: "Born a Crime: Stories from a South African Childhood",
    author: "Trevor Noah",
    genre: "Non-Fiction",
    publicationYear: "2016",
  },
  {
    id: 9,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Mystery",
    publicationYear: "2003",
  },
  {
    id: 10,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    genre: "Mystery",
    publicationYear: "2005",
  },
  {
    id: 11,
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
    publicationYear: "1892",
  },
  {
    id: 12,
    title: "In Cold Blood",
    author: "Truman Capote",
    genre: "Non-Fiction",
    publicationYear: "1966",
  },
];
